---
- name: Install Dovecot
  apt:
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-pop3d
    state: present

- name: Configure Dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart Dovecot
  service:
    name: dovecot
    state: restarted
