---
- name: Install Dovecot
  apt:
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-pop3d
    state: present

- name: Enable auth service in Dovecot part 1
  template:
    src: 10-master.conf.j2
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: '0644'
  register: dovecot_auth_config1

- name: Enable auth service in Dovecot part 2
  template:
    src: 10-ssl.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode: '0644'
  register: dovecot_auth_config2

- name: Enable auth service in Dovecot part 3
  template:
    src: 10-auth.conf.j2
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: '0644'
  register: dovecot_auth_config3

- name: Configure Dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  register: dovecot_config

- name: Configure SSL in Dovecot
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: '^ssl_cert ='
    line: 'ssl_cert = {{ ssl_directory }}/{{ mail_hostname }}/{{ ssl_certificate_name }}'
  register: dovecot_ssl_config

- name: Restart Dovecot
  service:
    name: dovecot
    state: restarted
  when: dovecot_auth_config1.changed or dovecot_auth_config2.changed or dovecot_auth_config3.changed or dovecot_config.changed or dovecot_ssl_config.changed
