- name: Get Dovecot logs from journalctl
  shell: journalctl -u dovecot --since "10 minutes ago"
  register: dovecot_journal_output
  become: true

- name: Write Dovecot logs to remote file
  copy:
    content: "{{ dovecot_journal_output.stdout }}"
    dest: /tmp/dovecot-journal.log
  become: true

- name: Fetch dovecot log
  fetch:
    src: /tmp/dovecot-journal.log
    dest: ./artifacts/dovecot.log
    flat: yes

- name: Remove temporary dovecot log file
  file:
    path: /tmp/dovecot-journal.log
    state: absent
  become: true