- name: Get Postfix logs from journalctl
  shell: journalctl -u postfix --since "10 minutes ago"
  register: postfix_journal_output
  become: true

- name: Write Postfix logs to remote file
  copy:
    content: "{{ postfix_journal_output.stdout }}"
    dest: /tmp/postfix-journal.log
  become: true

- name: Fetch postfix log
  fetch:
    src: /tmp/postfix-journal.log
    dest: ./artifacts/postfix.log
    flat: yes

- name: Remove temporary postfix log file
  file:
    path: /tmp/postfix-journal.log
    state: absent
  become: true