---
- name: Install Postfix
  apt:
    name: postfix
    state: present

- name: Configure Postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Postfix

- name: Configure submission
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: '0644'

- name: Configure SSL in Postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_tls_cert_file='
    line: 'smtpd_tls_cert_file={{ ssl_directory }}/{{ mail_hostname }}/{{ ssl_certificate_name }}'
  notify: Restart Postfix
