---
- name: Install Postfix
  apt:
    name: postfix
    state: present

- name: Configure Postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'

- name: Configure Postfix master.cf
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Postfix

- name: Restart Postfix
  service:
    name: postfix
    state: restarted
