---
- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Obtain SSL Certificate
  command:
    cmd: certbot certonly --webroot -w /var/www/html -d {{ mail_hostname }} --non-interactive --agree-tos --email {{ admin_email }}
  register: certbot_result
  ignore_errors: yes
  args:
    creates: "{{ ssl_directory }}/{{ mail_hostname }}/{{ ssl_certificate_name }}"

- name: Fetch certbot log on failure
  fetch:
    src: /var/log/letsencrypt/letsencrypt.log
    dest: ./artifacts/letsencrypt.log
    flat: yes
  when: certbot_result.failed

- name: Fail play if certbot failed
  fail:
    msg: "Certbot command failed, see letsencrypt.log artifact for details."
  when: certbot_result.failed
