---
- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Obtain SSL Certificate
  command:
    cmd: certbot certonly --webroot -w /var/www/html -d {{ mail_hostname }} --non-interactive --agree-tos --email {{ admin_email }}
  args:
    creates: "{{ ssl_directory }}/{{ mail_hostname }}/{{ ssl_certificate_name }}"
