---
- name: Uninstall Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: absent
    purge: yes

- name: Remove Postfix directories
  file:
    path: "{{ ssl_directory }}/{{ mail_hostname }}/{{ ssl_certificate_name }}"
    state: absent
