---
- name: Restart Dovecot
  service:
    name: dovecot
    state: restarted

- name: Restart Postfix
  service:
    name: postfix
    state: restarted

- name: Stop Postfix
  service:
    name: postfix
    state: stopped

- name: Stop Dovecot
  service:
    name: dovecot
    state: stopped
